export const milestones = [
  {
    idx: 0,
    text: [
      "Olá, nosso mundo anda meio caótico desde que o Elon Musk",
      "alterou a nossa simulação, mas descobrimos que ela foi criada",
      "utilizando HTML, CSS e Javascript. Nosso papel hoje é",
      "destruir bots defeituosos e tentar consertar parte do CSS.",
      " ",
      "O CSS é responsável pela parte visual do mundo, e um dos seus",
      "principais usos é na posição das coisas. Como você pode",
      "ver, tudo está bagunçado. Vamos matar alguns inimigos e",
      "tentar restaurar a ordem. Quanto mais inimigos matarmos,",
      "mais partes do mundo voltarão para suas posições corretas.",
      " ",
      "Use as setas do teclado para se movimentar,",
      "espaço para atacar e Esc para pausar.",
      " ",
      "Pressione 'E' para começar",
    ],
    font: "25px 'Press Start 2P'",
    textAlign: "center",
    fillStyle: "white",
    enemyQty: 0,
    posY: 200,
    posX: window.innerWidth / 2,
  },
  {
    idx: 1,
    text: [
      "Boa, você restaurou as leis da física!",
      "",
      "Mas como você pode perceber, algumas coisas continuam em preto e branco!",
      "",
      "O CSS pode nos ajudar com isso, setando cores em cada um dos elementos.",
      "Continue eliminando os bots para restaurar as cores do mundo.",
      "",
      "Não sei se você reparou, mas a simulação fica mais rápida conforme",
      "matamos mais inimigos, tome cuidado com isso.",
      "",
      "",
      "Pressione 'E' para continuar",
    ],
    font: "20px 'Press Start 2P'",
    textAlign: "center",
    fillStyle: "white",
    enemyQty: 45,
    posY: window.innerHeight / 2 - 200,
    posX: window.innerWidth / 2,
  },
  {
    idx: 2,
    text: [
      "Perfeito, cores recuperadas!",
      "",
      "Além das cores, o CSS permite aplicar filtros!",
      "Caso apareça algum inimigo diferente, mate-o e terá uma supresa.",
      "",
      "Para sair do modo especial, pressione 'S'.",
      "",
      "",
      "Pressione 'E' para continuar",
    ],
    font: "20px 'Press Start 2P'",
    textAlign: "center",
    fillStyle: "white",
    enemyQty: 130,
    posY: window.innerHeight / 2 - 150,
    posX: window.innerWidth / 2,
  },
  {
    idx: 3,
    text: [
      "Parabéns, você conseguiu recuperar boa parte do mundo!",
      "Ainda precisamos resolver algumas coisas usando Javascript,",
      "mas pode ser outro dia.",
      "",
      "",
      "Pressione 'E' para continuar",
      "Pressione 'R' a qualquer momento para recomeçar o jogo",
    ],
    font: "20px 'Press Start 2P'",
    textAlign: "center",
    fillStyle: "white",
    enemyQty: 200,
    posY: window.innerHeight / 2 - 150,
    posX: window.innerWidth / 2,
  },
  {
    idx: 4,
    text: ["Endgame"],
    font: "20px 'Press Start 2P'",
    textAlign: "center",
    fillStyle: "white",
    enemyQty: 200000,
    posY: window.innerHeight / 2 - 50,
    posX: window.innerWidth / 2,
  },
];
